name: misskey_streaming
version: 0.0.1-beta
homepage: https://librarylibrarian.com/
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"
description: A Flutter package that allows easy use of Misskey's Streaming API.
dependencies:
  flutter:
    sdk: flutter
  misskey_api_core: ^0.0.4-beta
  rxdart: ^0.28.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.33.0
  pubspec_dependency_sorter: ^1.0.5
platforms:
  ios:
  android:
repository: https://github.com/LibraryLibrarian/misskey_streaming
issue_tracker: https://github.com/LibraryLibrarian/misskey_streaming/issues
topics:
  - misskey
  - api
  - streaming
flutter: null
